services:
  api:
    build: .
    container_name: order-api
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    container_name: order-worker
    command: npm run worker
    env_file:
      - .env.production
    depends_on:
      - redis
      - postgres

  dbsync:
    build: .
    container_name: db-sync-worker
    command: npm run dbworker
    env_file:
      - .env.production
    depends_on:
      - postgres

  stream:
    build: .
    container_name: stream-worker
    command: npm run stream
    env_file:
      - .env.production
    depends_on:
      - redis

  limit:
    build: .
    container_name: limit-worker
    command: npm run limit
    env_file:
      - .env.production
    depends_on:
      - redis

  sniper:
    build: .
    container_name: sniper-worker
    command: npm run sniper
    env_file:
      - .env.production
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
